const tokenOf = {
  "+": 'PLUS',
  "-": 'DASH',
  ".": 'PERIOD',
  "'": 'SMALLQUOTE',
  '"': 'BIGQUOTE',
  "*": 'ASTERISK',
  "!": 'EXCLAIM',
  "?": 'QUESTION',
  "%": 'PERCENT',
  '@': 'AT',
  '(': 'LEFTPARENT',
  ')': 'RIGHTPARENT',
  '|': 'LINE',
  '=': 'EQUALS',
  '\\': 'BACKSLASH',
  '[': 'LEFTBRACKET',
  ']': 'RIGHTBRACKET',
  '&': 'AND',
  '^': 'POWER',
  "<": 'LEFTANGLE',
  ">": 'RIGHTANGLE',
  ";": "SEMI",
  '~': "SENO",
  ':': 'ISOPERATOR',
  '{': 'LEFTCURL',
  '}': 'RIGHTCURL'
}
exports.tokenOf = tokenOf